-- UniCourse Fase 2
-- Intencionalmente dejamos este seed sin usuarios ni perfiles de prueba.
-- Los flujos de registro, confirmación de correo y perfil deben probarse con cuentas reales
-- creadas desde /registro, no con datos heredados de versiones anteriores.
